baseURL = "https://lame.su/"
languageCode = "ru-ru"
title = "lame.su"
theme = "hugo-bearblog"

dateFormat = "2006-01-02"
enableRobotsTXT = true

# for image linking in posts
markup.goldmark.renderHooks.image.useEmbedded="fallback"
markup.goldmark.renderHooks.link.useEmbedded="fallback"
